Go mgt samples
firebase/snippets-go pull request #4
Opened 2017-12-02 12:10 UTC by avishalom

Go samples for the admin user management + custom claims

2017-12-04 16:03 UTC, samtstern commented on admin/main.go
> +	// alternatively
Is this second `alternatively` comment misplaced?

2017-12-04 16:04 UTC, samtstern commented on admin/main.go
> +	// see "CreateUser, above for syntax alteratives to (&auth.UserTo...{})"
I'd remove this comment since we don't know that this code snippet will always follow the previous one in docs.

2017-12-04 16:05 UTC, samtstern approved these changes
Just some minor comments, but LGTM

2017-12-04 21:38 UTC, hiranya911 requested changes
Please shadow the Node.js examples as much as possible. The samples in our pages should be functionally equivalent. Also need a few additional snippets to fully demonstrate custom claims support in Go.

2017-12-04 21:38 UTC, hiranya911 commented on admin/main.go
> +		log.Fatalf("error getting user %s: %v\n", uid, err)
Use Fatalln and Println and remove `\n` literals from the strings.

2017-12-04 21:38 UTC, hiranya911 commented on admin/main.go
> +		(&auth.UserToCreate{}).
Please unpack this to multiple lines:

```
r := &auth.UserToCreate{}.
           Email()
           ...
u, err := auth.CreateUser(r)
```

2017-12-04 21:38 UTC, hiranya911 commented on admin/main.go
> +		(&auth.UserToCreate{}).UID(uid).Email("user@example.com").PhoneNumber("+15555550100"))
Unpack

2017-12-04 21:38 UTC, hiranya911 commented on admin/main.go
> +	u2, err := client.CreateUser(context.Background(),
Just show this in the snippet. The former style is redundant.

2017-12-04 21:38 UTC, hiranya911 commented on admin/main.go
> +		(&auth.UserToUpdate{}).
Please unpack. And only show one example. No alternatives necessary.

2017-12-04 21:38 UTC, hiranya911 commented on admin/main.go
> +	// Iterating by pages 7 users at a time
Change to about 100 instead of 7. That is more realistic.

2017-12-04 21:38 UTC, hiranya911 commented on admin/main.go
> +		log.Printf("read user user: %v\n", user)
`log.Println("User: %v", user)`

Follow the log format used in Node.js sample snippets as much as possible.

2017-12-04 21:38 UTC, hiranya911 commented on admin/main.go
> +	err := client.SetCustomUserClaims(context.Background(), uid, nil)
Please remove. The snippet here should be equivalent to the Node.js snippet in the same page.

2017-12-04 21:38 UTC, hiranya911 commented on admin/main.go
> +	err = client.SetCustomUserClaims(context.Background(), uid, map[string]interface{}{"2custom": "2claims"})
Use the same claims set in the Node.js example (`admin = true`).

2017-12-04 21:38 UTC, hiranya911 commented on admin/main.go
> +}
Need more sample snippets to shadow the Node.js samples in https://firebase-dot-devsite.googleplex.com/docs/auth/admin/custom-claims

Specifically:
* Accessing claims via decoded ID tokens
* Accessing claims via a call to `GetUser()`
* Defining roles via backend script
* Incrementally updating claims

2017-12-07 21:04 UTC, hiranya911 approved these changes
LGTM with some nits. Please take a look before merging.

2017-12-07 21:04 UTC, hiranya911 commented on admin/main.go
> +func createUserWUID(ctx context.Context, client *auth.Client) *auth.UserRecord {
Nit: createUserWithUID

2017-12-07 21:04 UTC, hiranya911 commented on admin/main.go
> +
Remove whitespace

2017-12-07 21:04 UTC, hiranya911 commented on admin/main.go
> +	if adminVal, found := claims["admin"]; found {
Lets simplify this a bit by making a couple of assumptions.

```
if admin, ok := claims["admin"]; ok {
  if admin.(bool) {
    // Allow access ...
  }  
}
```

2017-12-07 21:04 UTC, hiranya911 commented on admin/main.go
> +	if adminVal, found := user.CustomClaims["admin"]; found {
Same here

2017-12-07 21:04 UTC, hiranya911 commented on admin/main.go
> +	iter2 := client.Users(context.Background(), "")
Lets inline the call to client.Users() and remove iter2

2017-12-07 21:20 UTC, merged